services: # we create the containers under this
  db: # our database container
    image: postgres:15-alpine # defining the version of the postgres to be used
    container_name: argus_postgres # name of this db container
    restart: always # Automatically restarts the container if it stops or Docker restarts
    environment:
      POSTGRES_USER: nimesh
      POSTGRES_PASSWORD: argusCapstone123
      POSTGRES_DB: argus_security_capstone
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data # path where the database files gets stored
    healthcheck: # commands to check if postgres is running properly before running the app
      test: ["CMD-SHELL", "pg_isready -U nimesh -d argus_security_capstone"]
      interval: 10s
      timeout: 5s
      retries: 5

  web: # fastapi container
    build: . # Builds the image using the Dockerfile in the current directory
    container_name: argus_fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mounts the current project directory into the container for live code changes
    environment:
      - DATABASE_URL=postgresql://nimesh:argusCapstone123@db:5432/argus_security_capstone
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: # creating a folder to save our database files